// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// pcl_ground_classify
IntegerVector pcl_ground_classify(NumericVector X, NumericVector Y, NumericVector Z, int MaxWinSize, float slope, float InitDist, float MaxDist);
RcppExport SEXP lidRExtra_pcl_ground_classify(SEXP XSEXP, SEXP YSEXP, SEXP ZSEXP, SEXP MaxWinSizeSEXP, SEXP slopeSEXP, SEXP InitDistSEXP, SEXP MaxDistSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Y(YSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< int >::type MaxWinSize(MaxWinSizeSEXP);
    Rcpp::traits::input_parameter< float >::type slope(slopeSEXP);
    Rcpp::traits::input_parameter< float >::type InitDist(InitDistSEXP);
    Rcpp::traits::input_parameter< float >::type MaxDist(MaxDistSEXP);
    rcpp_result_gen = Rcpp::wrap(pcl_ground_classify(X, Y, Z, MaxWinSize, slope, InitDist, MaxDist));
    return rcpp_result_gen;
END_RCPP
}
