# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib lidRExtra
#' @importFrom Rcpp sourceCpp
NULL

#' Internal version of ground_classify
#' @export
pcl_ground_classify <- function(X, Y, Z, MaxWinSize = 20L, slope = 1.0, InitDist = 0.5, MaxDist = 3.0) {
    .Call('lidRExtra_pcl_ground_classify', PACKAGE = 'lidRExtra', X, Y, Z, MaxWinSize, slope, InitDist, MaxDist)
}

